apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: api
        image: hello-api:latest
        imagePullPolicy: Never         # ← add this
        ports:
        - containerPort: 5000
      - name: frontend
        image: hello-frontend:latest
        imagePullPolicy: Never         # ← add this
        ports:
        - containerPort: 80